import requests from "../utils/requests";
import { useSession } from "next-auth/client";
import Footer from "../components/Footer";
import HomePage from "../components/HomePage";
import Navbar from "../components/Navbar";
import * as am4core from "@amcharts/amcharts4/core";
import * as am4charts from "@amcharts/amcharts4/charts";
import am4themes_animated from "@amcharts/amcharts4/themes/animated";

export default function Home() {
  const [session, loading] = useSession();

  return (
    <div className="bg-slate-500 h-full w-full">
      {/* <Image
        alt="background flags"
        src="/public/flags2.jpg"
        layout="fill"
        objectFit="cover"
        quality={100}
      /> */}
      <Navbar />
      <HomePage />
      <Footer />
    </div>
  );
}

// // Randomiser
// function shuffleArray(array, x) {
//   let curId = array.length;
//   // There remain elements to shuffle
//   while (0 !== curId) {
//     // Pick a remaining element
//     let randId = Math.floor(Math.random() * curId);
//     curId -= 1;
//     // Swap it with the current element.
//     let tmp = array[curId];
//     array[curId] = array[randId];
//     array[randId] = tmp;
//   }
//   return array;
// }

/*export default function Home(props) {
  return (
    <div className="h-screen bg-slate-300">
      <Head>
        <title>Flags Test - Game</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  );
}*/

// //  les statics
// export async function getStaticProps() {
//   //fetch la liste des pays de la zone demandée
//   const reqCountries = await fetch(requests.fetchEurope.url);
//   const dataCountries = await reqCountries.json();

//   // transforme la liste json en array
//   const countries = Array.from(dataCountries);

//   //crée un array contenant les codes ISO qu'on pourra randomiser
//   const codeArray = [];
//   countries.forEach((country) => {
//     codeArray.push(country.cca3);
//   });

//   // Deep copy (pour éviter l'assignation par référence) de l'array code
//   var randomFlags = codeArray.slice();
//   var randomNames = codeArray.slice();

//   // Randomisation liste pour les drapeaux
//   randomFlags = shuffleArray(randomFlags);

//   //Randomisation liste pour les pays à trouver
//   randomNames = shuffleArray(randomNames);

//   //crée un dictionnaire association cca3 : infos pays
//   var indexedCountries = {};
//   for (let i = 0; i < countries.length; i++) {
//     let country = countries[i];
//     indexedCountries[country.cca3] = country;
//   }

//   // retourne les props
//   return {
//     props: {
//       index: indexedCountries,
//       codes: codeArray,
//       randomNames: randomNames,
//       randomFlags: randomFlags,
//     },
//   };
// }

// import Head from "next/head";
// import Results from "../components/Results";
// import requests from "../utils/requests";

// export default function Home(props) {
//   return (
//     <div className="h-screen bg-slate-300">
//       <Head>
//         <title>Flags Test - Game</title>
//         <meta name="description" content="Generated by create next app" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>
//       <Results results={props} />
//     </div>
//   );
// }

// export async function getServerSideProps() {
//   const reqCountries = await fetch(requests.fetchEurope.url);
//   const dataCountries = await reqCountries.json();

//   return {
//     props: { data: dataCountries },
//   };
// }
